### ISSUE TITLE
我试用过一次 `ufct`以后，每次打开工程文件都会被修改一次文件注释

### ISSUE THREAD

**Issue by Jokemac** [HansenCCC/YPTools#2]
我想知道怎么可以停下来

**Comment by Jokemac** [comment]
// YPTools Auto Update Create Date https://github.com/HansenCCC/YPTools
这个注释在Git下每次都会被修改

**Comment by HansenCCC** [comment]
你是不想要注释吗

**Comment by Jokemac** [comment]
> 你是不想要注释吗

不是的，注释还是要的。
现在的情况是这样 我在2月10号使用了`ufct`，然后文件时间都更新了，并且出现了这个注释，这个没问题。
但是我2月11号打开一个文件没有修改任何东西，我的git就提示这一行注释有修改，所有打开过的文件git都提示这一行注释有修改。

**Comment by Jokemac** [comment]
> > 你是不想要注释吗
> 
> 不是的，注释还是要的。 现在的情况是这样 我在2月10号使用了`ufct`，然后文件时间都更新了，并且出现了这个注释，这个没问题。 但是我2月11号打开一个文件没有修改任何东西，我的git就提示这一行注释有修改，所有打开过的文件git都提示这一行注释有修改。

![FELpy.png](https://i.328888.xyz/2023/03/03/FELpy.png)

**Comment by HansenCCC** [comment]
你可能又执行了一下ufct命令，这个注释，每执行一次会多一行。😂

**Comment by HansenCCC** [comment]
我的微信是这个13767141841，你还有问题可以直接来问
